### ISSUE TITLE
Docker image entrypoint is not handled correctly when using Gitlab CI/CD

### ISSUE THREAD

**Issue by realkarmakun** [ComunidadAylas/PackSquash#135]
### Distribution

Other (please describe in the "Additional context" section)

### Bug description

Packsquash's Docker Image is broken when supplying empty entrypoint (or not supplying entrypoint at all) in Gitlab CI/CD enviroment.

When supplying empty entrypoint in Gitlab CI/CD (as recommended in Gitlab documentation) we get following error:
```
ERROR: Job failed (system failure): Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "sh": executable file not found in $PATH: unknown (exec.go:73:0s)
```

### Reproduction steps

1. Create one of the following Gitlab CI/CD jobs utilizing official PackSquash Docker image:

Empty entrypoint:
```yaml
build-job:
  stage: build
  image: 
    name: ghcr.io/comunidadaylas/packsquash:edge
    entrypoint: [""]
  script:
    - /usr/bin/packsquash --appimage-extract-and-run packsquash-config.toml
```

Not supplying entrypoint (fallback to ENTRYPOINT in Dockerfile):
```yaml
build-job:
  stage: build
  image: 
    name: ghcr.io/comunidadaylas/packsquash:edge
  script:
    - /usr/bin/packsquash --appimage-extract-and-run packsquash-config.toml
```

2. Run the jobs
3. Observe failed jobs

### Expected behavior

Either both or any job above should succeed (as it's both should be valid ways to run docker image, or one of them should be at least)

### Additional context

I suppose this happens as you use distroless image (Which makes sense that there is no bash and Docker can't fallback to it)

We can supply `script` commands as `entrypoint`, but that's against best practices and having `script` field in mandatory.

Also we can't put anything but PackSquash in `entrypoint` because of distroless image (Can't put echo "Starting PackSquash" for example)

Also I can't supply just PackSquash binary command without any args as it expects config file and fails hence failing a job.

Right now we can supply both command in `entrypoint` and `script` field but that just doing same job twice.

Possible solutions:
1. Don't use "distroless" images or have bash shell in PackSquash image one way or another to supply empty entrypoint
2. Add command for printing PackSquash version that doesn't fail (Like `packsquash version` or something like this that returns 0) so Job will not be marked as failed after executing entrypoint like this`["/usr/bin/packsquash", "--appimage-extract-and-run", "version"]` so we won't be supplying entrypoint at all.

Also,
In cases when we don't supply entrypoint of our own - it is broken as well since entrypoint is Dockerfile is `["packsquash", "--appimage-extract-and-run"]` and it should be `["/usr/bin/packsquash", "--appimage-extract-and-run"]` or alternatively `/usr/bin/packsquash` needs to be in PATH variable.

**Comment by AlexTMjugador** [comment]
Thank you for the well-described bug report!

Indeed the usage of the distroless base image means that there is no shell in the container. I considered this an acceptable trade-off in exchange for smaller image sizes, decreased hypothetical attack surface and ease of audit, as PackSquash doesn't need a shell, and I thought users neither would (if you really need it, you can bind-mount a statically-linked Busybox shell and run it from the container, but that arguably is a bit complicated).

Now, I will address the particular thoughts and facts you've shared.

> Also I can't supply just PackSquash binary command without any args as it expects config file and fails hence failing a job.

The current intended way to pass arguments to PackSquash is to do so directly to the image-defined entrypoint, as in this `docker run` invocation (note how it also bind-mounts a directory to expose the options file to the container, and the generated ZIP file to the host):

```
$ docker run -v /path/to/host/dir/:/path/to/container/dir \
    ghcr.io/comunidadaylas/packsquash:edge \
    /path/to/container/dir/packsquash-config.toml
```

I've decided to set up the entrypoint in this way because, after reading the Docker documentation, I found it more idiomatic, and makes the container feel more like if it was the PackSquash binary, which is something I want. For example, this is how web server images work.

> We can supply script commands as entrypoint, but that's against best practices and having script field in mandatory.

Yes, I agree that's a bad idea too.

> Also we can't put anything but PackSquash in entrypoint because of distroless image (Can't put echo "Starting PackSquash" for example)

You could execute those commands before PackSquash runs; for example, in a previous stage (or, if there are no other stages, the [`.pre` stage](https://docs.gitlab.com/ee/ci/yaml/#stage-pre)).

Is there any good reason to do such commands on the PackSquash image itself? Even though this may be a relatively minor and unimportant concern, I don't like the idea of me doing some random change in the PackSquash image, such as upgrading or downgrading the C library, and potentially breaking some random build because of that. It may be inconvenient, but I think it's better if people can only take for granted that the PackSquash image can only run PackSquash to begin with.

> Add command for printing PackSquash version that doesn't fail (Like packsquash version or something like this that returns 0) so Job will not be marked as failed after executing entrypoint like this["/usr/bin/packsquash", "--appimage-extract-and-run", "version"] so we won't be supplying entrypoint at all.

PackSquash already has such an argument, `-v` (or `--version`), which is used by the GitHub Action:

https://github.com/ComunidadAylas/PackSquash/blob/6f40332118196bbc68074f199121526dd8a013b7/packages/packsquash_cli/src/bin/packsquash/main.rs#L93-L97

Is this what you are looking for?

> In cases when we don't supply entrypoint of our own - it is broken as well since entrypoint is Dockerfile is ["packsquash", "--appimage-extract-and-run"] and it should be ["/usr/bin/packsquash", "--appimage-extract-and-run"] or alternatively /usr/bin/packsquash needs to be in PATH variable.

[The Docker documentation](https://docs.docker.com/engine/reference/run/#env-environment-variables) states that the `PATH` environment variable is set to a value that contains the directory where the AppImage is, and it worked fine on my Linux box. But if for some reason that is not the case in your environment, due to the way GitLab runs images or things like that, I agree that it's better to err on the verbose side and specify an absolute path.

On the GitLab CI workflow you are using, in particular this one:

```yaml
build-job:
  stage: build
  image: 
    name: ghcr.io/comunidadaylas/packsquash:edge
    entrypoint: [""]
  script:
    - /usr/bin/packsquash --appimage-extract-and-run packsquash-config.toml
```

From what I can understand from the [GitLab docs](https://docs.gitlab.com/ee/ci/docker/using_docker_images.html) (I'm not an expert on their CI/CD product, so feel free to take this with a grain of salt), this is what is happening on the workflow:

- A job named `build-job` is defined, that runs on the `build` stage, in parallel with other jobs in that stage, if any.
- The `build-job` requests being run on the PackSquash Docker image, overriding its entrypoint to run a shell.
- The `script` key lists commands that are run by a shell as a part of the job.

Because the job is being run on the PackSquash Docker image, which lacks a shell, there is no way that workflow would work. The goal here is running the PackSquash Docker image as a part of the CI process, not running a CI job script on the Docker image itself!

This is straightforward to do on GitHub Actions, because an action step can be a container invocation, and I find that pretty intuitive. However, in my opinion, the GitLab CI/CD documentation is unclear on how you would do such a sensible thing on their platform. What comes to my mind is leveraging the GitLab stages feature to run PackSquash on a separate job and stage, in-between other commands. The following workflow should work to illustrate my idea, but I didn't test it, so it probably won't work as-is:

```yaml
stages:
  - pre-build
  - build
  - post-build

pre-build-job:
  stage: pre-build
  script:
    - echo "Whatever you want to do before PackSquash runs"

build-job:
  stage: build

  # Maybe you need to specify an image there too, like this?
  # image:
  #   name: whatever-image

  services:
    - name: ghcr.io/comunidadaylas/packsquash:edge
      alias: packsquash
      # The GitLab docs at
      # https://docs.gitlab.com/ee/ci/services/index.html#available-settings-for-services
      # imply this is equivalent to passing extra args to docker run
      command: /path/to/options-file.toml

  script:
    # This a dummy script. I think that jobs without a script upset GitLab
    - echo "Running PackSquash"

post-build-job:
  stage: post-build
  script:
    - echo "Whatever you want to do after PackSquash runs"
```

Another, less hacky way I can come up with is using `docker run` directly, [inspired by this piece of documentation](https://docs.gitlab.com/ee/ci/services/index.html#using-services-with-docker-run-docker-in-docker-side-by-side), but I didn't test it either:

```yaml
access-service:
  stage: build
  image: docker:19.03.1
  services:
    - docker:dind                    # necessary for docker run
  script: |
    docker run -v "$(pwd)":"$(pwd)" --workdir "$(pwd)" \
    ghcr.io/comunidadaylas/packsquash:edge \
    packsquash-config.toml
```

Please let me know if anything I've said was relevant for you.

**Comment by realkarmakun** [comment]
Sorry for not being clear enough about echo, it's just a dummy script to make configuration possible since script field is mandatory in Gitlab CI/CD. My main issue is that I can't run PackSquash any way on Gitlab CI/CD right now, no matter the entrypoint. 
If I supply empty - it will fail without bash. 
If I don't supply it will fail saying I need to specify config file (since it's configured this way in ENTRYPOINT)
If I supply packsquash command (`["/usr/bin/packsquash", "--appimage-extract-and-run"]`) it will fail as well like above.
I was hoping to put some dummy script in entrypoint, to run packsquash in script but that won't work (no bash)
I also tried putting dummy script in script, and running packsquash command in entrypoint, but when image starts it seems like image is not yet aware of git repository files thus not aware of packsquash-config.

I need to try running it with -v option in entrypoint, but I'm thinking it will just close container and I won't be able to run commands in script at all. Job will succeed but no work will be done.

I do see a way to run this with Docker-In-Docker (dind) you mentioned, but I'm not particularly fond of this solution. I personally try to avoid running docker daemon in docker containers at all costs. Maybe gitlab service will be a way to go, I need to try it first. Anyway distroless image doesn't seem to work with gitlab ci/cd out of the box and it makes me sad :(

**Comment by AlexTMjugador** [comment]
I agree with you that the ways there are to run the PackSquash Docker image on GitLab CI are far from elegant :sweat_smile:

I would not mind changing the Docker image to contain a shell if that made it more useful, but I don't think that's the best solution for the reasons I've stated previously.

I find it surprising that GitLab CI is making us bend over backward so much to achieve something that, in my opinion, should be pretty straightforward. Are we getting something wrong? How do other people deal with images similar to the PackSquash one?

**Comment by realkarmakun** [comment]
> How do other people deal with images similar to the PackSquash one?
Seems like dind is the only option :( I'll go with it then. Really not using dind is just my personal preference. Outside of Gitlab CI/CD Packsquash docker image looks solid 👍 I'll be closing this then.

**Comment by realkarmakun** [comment]
So here is my Gitlab CI/CD configuration to run PackSquash docker image using Docker-in-Docker (Giltab Runner Docker executor) if anyone runs into issues I had
### Gitlab Runner config 
Following lines need to be added in `[runners.docker]` field:
```toml
priveleged = true
volumes = ["/certs/client", "/cache"]
```
I would recommend using different runner  then usual since `priveleged` widens attack surface and exposes host to privilege escalation disabling security mechanisms.

### Gitlab job
Specify docker version to make builds more predictable. Latest versions can break your pipeline with some kind of change.
```yaml
build-job:
  stage: build
  image: docker:20.10.16
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:20.10.16-dind
  before_script: 
    - docker info
  script: |
    docker run -v "$(pwd)":"$(pwd)" --workdir "$(pwd)" \
    ghcr.io/comunidadaylas/packsquash:edge \
    packsquash-config.toml
  artifacts:
    paths:
      - rp.zip
```
`tcp://docker:2375` comes from dind service name (e.g. `docker:20.10.16-dind`). If you rename it to something else `DOCKER_HOST` variable will need to be adjusted

@AlexTMjugador I have a feeling this needs to be somewhere in the docs along with running the docker container directly. Feel free to copy/change this
