### ISSUE TITLE
Faulty ZIPs for Minecraft 1.21.4 with obfuscation

### ISSUE THREAD

**Issue by scrayos** [ComunidadAylas/PackSquash#345]
### Distribution

Linux x64 executable

### Bug description

When using PackSquash (binary compiled from commit https://github.com/ComunidadAylas/PackSquash/commit/aaf817a1bd341ef1855a476f1394d5417e87b105) with the following config, the resulting ZIP does not work in Minecraft as of 1.21.4 (worked previously):

```toml
pack_directory = 'src'
output_file_path = 'resources.min.zip'

zip_spec_conformance_level = 'disregard'
size_increasing_zip_obfuscation = true
```

This may be, because Minecraft 1.21.4 (or maybe even earlier) introduced a new `items` directory within namespaces.

If I either change `size_increasing_zip_obfuscation` to false or `zip_spec_conformance_level` to `balanced`, the ZIP file works again.

### Reproduction steps

1. Use the minimal resource pack I provided in the attached files section
2. Compress the resource pack with PackSquash with the supplied packsquash.toml
3. Try to load this resource pack in Minecraft
4. Give yourself a normal stick
5. Observe that the model is not swapped/set

### Expected behavior

I expect my custom model to be present.

### Attached files

[pq-test.zip](https://github.com/user-attachments/files/18140356/pq-test.zip)
